<?php
/**
 * Title: Final da jornada
 * Slug: sesilab/caminho-final
 * Categories: caminho
 * Post Types: caminho
 * Source: theme
 * Block Types: core/post-content
 */
?>

<!-- wp:greenshift-blocks/image {"id":"gsbp-56dc2e6","inlineCssStyles":"#gspb_image-id-gsbp-56dc2e6 img{vertical-align:top;}#gspb_image-id-gsbp-56dc2e6 img{display:inline-block;box-sizing:border-box;max-width:100%;height:auto;}body.gspb-bodyfront #gspb_image-id-gsbp-56dc2e6{position:fixed;z-index:9;top:18px;left:18px;}#gspb_image-id-gsbp-56dc2e6 img{transform:translateX(0px) translateY(0px);}","interactionLayers":[{"actions":[{"actionname":"animation","aopts":[{"type":"scale","value":"1.1"}],"aprops":[]}],"env":"no-action","triggerData":{"trigger":"mouse-enter"}},{"actions":[{"actionname":"animation","aopts":[{"type":"scale","value":"1.0"}]}],"env":"no-action","triggerData":{"trigger":"mouse-leave"}}],"originalWidth":102,"originalHeight":83,"position":{"positionType":["fixed","","",""],"positions":{"values":{"top":["18px"],"left":["18px"],"bottom":[null],"right":[null]}},"fastPositionType":["top","left"],"Zindex":9},"csstransform":{"translateX":["0px"],"translateY":["0px"]},"mediaurl":"https://tainacan.hml.sesi.org.br/wp-content/uploads/2024/08/5.1_jogo_caminhos_da_inovacao_btn_sair.png","mediaid":475,"alt":"Sair","title":"Sair","href":"/caminho/inicio","linkTitle":"Sair"} -->
    <div class="wp-block-greenshift-blocks-image gspb_image gspb_image-id-gsbp-56dc2e6" id="gspb_image-id-gsbp-56dc2e6"><a href="/caminho/inicio" title="Sair" rel="noopener"><img src="https://tainacan.hml.sesi.org.br/wp-content/uploads/2024/08/5.1_jogo_caminhos_da_inovacao_btn_sair.png" data-src="" alt="Sair" loading="lazy" width="102" height="83" title="Sair" data-gspbactions="[{&quot;actions&quot;:[{&quot;actionname&quot;:&quot;animation&quot;,&quot;aopts&quot;:[{&quot;type&quot;:&quot;scale&quot;,&quot;value&quot;:&quot;1.1&quot;}],&quot;aprops&quot;:[]}],&quot;env&quot;:&quot;no-action&quot;,&quot;triggerData&quot;:{&quot;trigger&quot;:&quot;mouse-enter&quot;}},{&quot;actions&quot;:[{&quot;actionname&quot;:&quot;animation&quot;,&quot;aopts&quot;:[{&quot;type&quot;:&quot;scale&quot;,&quot;value&quot;:&quot;1.0&quot;}]}],&quot;env&quot;:&quot;no-action&quot;,&quot;triggerData&quot;:{&quot;trigger&quot;:&quot;mouse-leave&quot;}}]"/></a></div>
<!-- /wp:greenshift-blocks/image -->

<!-- wp:cover {"url":"https://tainacan.hml.sesi.org.br/wp-content/uploads/2024/09/jogo_caminhos_da_inovacao_final_background.png","id":577,"dimRatio":0,"isUserOverlayColor":true,"minHeight":100,"minHeightUnit":"vh","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|80","bottom":"var:preset|spacing|80"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-cover alignfull" style="padding-top:var(--wp--preset--spacing--80);padding-bottom:var(--wp--preset--spacing--80);min-height:100vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background wp-image-577" alt="" src="https://tainacan.hml.sesi.org.br/wp-content/uploads/2024/09/jogo_caminhos_da_inovacao_final_background.png" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:greenshift-blocks/container {"id":"gsbp-1194d0b","inlineCssStyles":".gspb_container-id-gsbp-1194d0b{flex-direction: column;box-sizing: border-box;}#gspb_container-id-gsbp-1194d0b.gspb_container \u003e p:last-of-type{margin-bottom:0}.gspb_container{position:relative;}#gspb_container-id-gsbp-1194d0b.gspb_container{display:flex;flex-direction:row;flex-wrap:wrap;justify-content:space-evenly;align-content:flex-start;align-items:center;row-gap:42px;column-gap:42px;}@media (max-width: 991.98px){#gspb_container-id-gsbp-1194d0b.gspb_container{flex-wrap:wrap;}}@media (max-width: 575.98px){#gspb_container-id-gsbp-1194d0b.gspb_container{align-content:flex-start;}}#gspb_container-id-gsbp-1194d0b.gspb_container{padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;}","flexbox":{"type":"flexbox","flexDirection":["row"],"justifyContent":["space-evenly"],"alignContent":["flex-start",null,null,"flex-start"],"flexWrap":["wrap","wrap"],"customchildorder":false,"orderitems":[[1,2]],"alignItems":["center"],"childNumber":2,"columngap":["42px"],"rowgap":["42px"]},"spacing":{"margin":{"values":{},"locked":false},"padding":{"values":{"top":["0px"],"right":["0px"],"bottom":["0px"],"left":["0px"]},"locked":false}}} -->
<div class="wp-block-greenshift-blocks-container gspb_container gspb_container-gsbp-1194d0b" id="gspb_container-id-gsbp-1194d0b"><!-- wp:greenshift-blocks/container {"id":"gsbp-b061cd3","inlineCssStyles":".gspb_container-id-gsbp-b061cd3{flex-direction: column;box-sizing: border-box;}#gspb_container-id-gsbp-b061cd3.gspb_container \u003e p:last-of-type{margin-bottom:0}.gspb_container{position:relative;}@media (max-width: 991.98px){body.gspb-bodyfront #gspb_container-id-gsbp-b061cd3.gspb_container{order:-1;}}body.gspb-bodyfront #gspb_container-id-gsbp-b061cd3.gspb_container{flex-grow:0;flex-shrink:1;}@media (max-width: 991.98px){body.gspb-bodyfront #gspb_container-id-gsbp-b061cd3.gspb_container{flex-grow:1;flex-shrink:0;flex-basis:100%;}}#gspb_container-id-gsbp-b061cd3.gspb_container{display:flex;flex-direction:column;align-items:center;row-gap:42px;column-gap:42px;}body.gspb-bodyfront #gspb_container-id-gsbp-b061cd3.gspb_container{position:sticky;top:0px;align-self:start;}#gspb_container-id-gsbp-b061cd3.gspb_container{transition-duration:0.8s;}#gspb_container-id-gsbp-b061cd3.gspb_container{transition-timing-function:ease;}#gspb_container-id-gsbp-b061cd3.gspb_container{opacity: 0;transition-property: opacity, transform;}#gspb_container-id-gsbp-b061cd3.gspb_container.aos-animate,#gspb_container-id-gsbp-b061cd3.gspb_container[data-gs-aos]{opacity: 1;transform: translateZ(0);}#gspb_container-id-gsbp-b061cd3.gspb_container{transform: translate3d(60px, 0, 0);}","flexGrow":["0","1"],"flexShrink":["1","0"],"flexBasis":[null,"100%"],"order":[null,"-1"],"flexbox":{"type":"flexbox","flexDirection":["column"],"alignItems":["center"],"columngap":["42px"],"rowgap":["42px"]},"animation":{"duration":800,"easing":"ease","type":"fade-left"},"spacing":{"margin":{"values":{"left":[null,0],"right":[null]},"locked":false},"padding":{"values":{},"locked":false}},"position":{"positionType":["sticky","","",""],"positions":{"values":{"top":["0px"]}}},"blockWidth":{"customWidth":{"value":[]},"customHeight":{"value":[]},"widthType":"custom"}} -->
<div class="wp-block-greenshift-blocks-container gspb_container gspb_container-gsbp-b061cd3" id="gspb_container-id-gsbp-b061cd3" data-aos="fade-left" data-aos-easing="ease" data-aos-duration="800"><!-- wp:image {"id":589,"width":"auto","height":"420px","aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","align":"center","className":"caminho-personagens","style":{"layout":{"selfStretch":"fit","flexSize":null}}} -->
<figure class="wp-block-image aligncenter size-full is-resized caminho-personagens"><img src="https://tainacan.hml.sesi.org.br/wp-content/uploads/2024/09/teste_caminhos6.png" alt="" class="wp-image-589" style="aspect-ratio:1;object-fit:cover;width:auto;height:420px"/></figure>
<!-- /wp:image -->

<!-- wp:greenshift-blocks/image {"id":"gsbp-2c73bd4","inlineCssStyles":"#gspb_image-id-gsbp-2c73bd4 img{object-fit:fill;}#gspb_image-id-gsbp-2c73bd4 img{vertical-align:top;}#gspb_image-id-gsbp-2c73bd4 img{display:inline-block;box-sizing:border-box;max-width:100%;height:auto;}","interactionLayers":[{"actions":[{"actionname":"animation","aopts":[{"type":"scale","value":"1.075"}]}],"env":"action","triggerData":{"trigger":"mouse-enter"}},{"actions":[{"actionname":"animation","aopts":[{"type":"scale","value":"1"}]}],"env":"action","triggerData":{"trigger":"mouse-leave"}}],"scale":["fill"],"originalWidth":231,"originalHeight":154,"mediaurl":"https://tainacan.hml.sesi.org.br/wp-content/uploads/2024/09/jogo_caminhos_da_inovacao_final_recomecar.png","mediaid":586,"alt":"","title":"Recomeçar","href":"/caminho/inicio","linkTitle":"Recomeçar"} -->
<div class="wp-block-greenshift-blocks-image gspb_image gspb_image-id-gsbp-2c73bd4" id="gspb_image-id-gsbp-2c73bd4"><a href="/caminho/inicio" title="Recomeçar" rel="noopener"><img src="https://tainacan.hml.sesi.org.br/wp-content/uploads/2024/09/jogo_caminhos_da_inovacao_final_recomecar.png" data-src="" alt="" loading="lazy" width="231" height="154" title="Recomeçar" data-gspbactions="[{&quot;actions&quot;:[{&quot;actionname&quot;:&quot;animation&quot;,&quot;aopts&quot;:[{&quot;type&quot;:&quot;scale&quot;,&quot;value&quot;:&quot;1.075&quot;}]}],&quot;env&quot;:&quot;action&quot;,&quot;triggerData&quot;:{&quot;trigger&quot;:&quot;mouse-enter&quot;}},{&quot;actions&quot;:[{&quot;actionname&quot;:&quot;animation&quot;,&quot;aopts&quot;:[{&quot;type&quot;:&quot;scale&quot;,&quot;value&quot;:&quot;1&quot;}]}],&quot;env&quot;:&quot;action&quot;,&quot;triggerData&quot;:{&quot;trigger&quot;:&quot;mouse-leave&quot;}}]"/></a></div>
<!-- /wp:greenshift-blocks/image --></div>
<!-- /wp:greenshift-blocks/container -->

<!-- wp:greenshift-blocks/container {"id":"gsbp-66e1de4","inlineCssStyles":".gspb_container-id-gsbp-66e1de4{flex-direction: column;box-sizing: border-box;}#gspb_container-id-gsbp-66e1de4.gspb_container \u003e p:last-of-type{margin-bottom:0}.gspb_container{position:relative;}body.gspb-bodyfront #gspb_container-id-gsbp-66e1de4.gspb_container{flex-basis:55%;}@media (max-width: 991.98px){body.gspb-bodyfront #gspb_container-id-gsbp-66e1de4.gspb_container{flex-basis:100%;}}","flexBasis":["55%","100%"]} -->
<div class="wp-block-greenshift-blocks-container gspb_container gspb_container-gsbp-66e1de4" id="gspb_container-id-gsbp-66e1de4"><!-- wp:greenshift-blocks/text {"id":"gsbp-248478b","inlineCssStyles":".gspb_text-id-gsbp-248478b{font-size:clamp(1.25rem, 1.3vw, 1.45rem);}.gspb_text-id-gsbp-248478b{line-height:clamp(2rem, 2.125vw, 2.25rem);}","textContent":"Sua instituição firmou um acordo de colaboração para pesquisa internacional. Após finalizar o cadastro prévio de remessa da amostra, conforme determina a legislação brasileira, a parceria entre as duas universidades pode seguir em frente e você parte para uma nova etapa na Ásia!\u003cbr\u003e\u003cbr\u003eEsse intercâmbio permitiu o acesso a tecnologias ainda não disponíveis no Brasil, mas o uso de patrimônio genético foi igualmente indispensável. Com o tempo, seu produto poderá ser comercializado com potencial sucesso e a lei que assegura a repartição de benefícios garantirá que o valor seja distribuído de maneira justa e equitativa entre todas as partes.\u003cbr\u003e\u003cbr\u003eSeu caminho pela inovação termina por aqui!","typography":{"textShadow":{},"useFluid":true,"fluidSizeMin":"1.25rem","fluidSizePerfect":"1.3vw","fluidSizeMax":"1.45rem","fluidLineMin":"2rem","fluidLinePerfect":"2.125vw","fluidLineMax":"2.25rem"}} -->
<div id="gspb_text-id-gsbp-248478b" class="gspb_text gspb_text-id-gsbp-248478b ">Sua instituição firmou um acordo de colaboração para pesquisa internacional. Após finalizar o cadastro prévio de remessa da amostra, conforme determina a legislação brasileira, a parceria entre as duas universidades pode seguir em frente e você parte para uma nova etapa na Ásia!<br><br>Esse intercâmbio permitiu o acesso a tecnologias ainda não disponíveis no Brasil, mas o uso de patrimônio genético foi igualmente indispensável. Com o tempo, seu produto poderá ser comercializado com potencial sucesso e a lei que assegura a repartição de benefícios garantirá que o valor seja distribuído de maneira justa e equitativa entre todas as partes.<br><br>Seu caminho pela inovação termina por aqui!</div>
<!-- /wp:greenshift-blocks/text --></div>
<!-- /wp:greenshift-blocks/container --></div>
<!-- /wp:greenshift-blocks/container --></div></div>
<!-- /wp:cover -->